### ISSUE TITLE
Support VS 2019

### ISSUE THREAD

**Issue by yhvicey** [Elders/VSE-FormatDocumentOnSave#13]
When open VS 2019 preview with this extension there will be a warning in ActivityLog.xml:

> Extension 'Format document on Save' uses the 'synchronous auto-load' feature of Visual Studio. This feature will no longer be supported in a future Visual Studio 2019 update, at which point this extension will not work. Please contact the extension vendor to get an update. (UI Context: {adfc4e64-0397-11d1-9f4e-00a0c911004f} Package Guid: {2f4fac85-be4e-4d7a-8c74-93cc4389b427})

**Comment by mynkow** [comment]
@yhvicey I am about to publish the new version. Please give it a try and if you still see this error please reopen this issue here. Keep in mind that I was not able to reproduce this on my machine on first place so I rely on you for a feedback.

Thank you

**Comment by yhvicey** [comment]
> @yhvicey I am about to publish the new version. Please give it a try and if you still see this error please reopen this issue here. Keep in mind that I was not able to reproduce this on my machine on first place so I rely on you for a feedback.
> 
> Thank you

Ok. I'm using VS 16 version 16.0.0 Preview 1.1.

**Comment by mynkow** [comment]
I see, I am a bit behind.

The package have to be live now => v1.20

**Comment by yhvicey** [comment]
Not sure why but VS 2019 cannot install version 1.20, even if I manually uninstall and then reinstall it.

**Comment by mynkow** [comment]
Hey @yhvicey 
I was able to install/uninstall the latest version with `VS 16 version 16.0.0 Preview 1.1`

However I still get the warning in VS and have no idea why. Need to ask someone from Microsoft. Will keep you updated.

BTW, what error you get when you try to install 1.20?

**Comment by yhvicey** [comment]
I remove the extension, download the .vsix file, installed and the installer reports the installation is successful - however when I check the installed version it shows 1.19. I have no idea why this happened.

**Comment by yhvicey** [comment]
I checked the downloaded .vsix file and found the version in `extension.vsixmanifest` is still 1.19. Is this the root cause?

**Comment by mynkow** [comment]
#16
