### ISSUE TITLE
use "eslint --fix" as custom command

### ISSUE THREAD

**Issue by giolvani** [Elders/VSE-FormatDocumentOnSave#15]
It would be very helpful if as the command I could use "eslint --fix" as a formatter.

**Comment by mynkow** [comment]
@giolvani did you try to set this command?

**Comment by giolvani** [comment]
I did, but nothing happened. In addition, also, I would like to use the local eslint installation, rather than global installation.

![image](https://user-images.githubusercontent.com/2387872/50287954-a80d1a00-044b-11e9-8be8-a4e948e10313.png)

**Comment by mynkow** [comment]
I am not sure how eslint works and what is the integration with VS. This extension is only capable of executing VS Commands. If you can create VSCommand which invokes `eslint --fix` then it will work for you.

 VSCommands => https://docs.microsoft.com/en-us/visualstudio/ide/reference/visual-studio-commands?view=vs-2017

**Comment by giolvani** [comment]
I was able to create only an "External Tool", but the commando I did not.

**Comment by giolvani** [comment]
I also try to execute the command directly but does not work as well...

```cmd.exe /c "$(ProjectDir)node_modules\.bin\eslint --fix $(ItemPath)"```
![image](https://user-images.githubusercontent.com/2387872/50296242-33dd7100-0461-11e9-8621-61247fac264d.png)

**Comment by mynkow** [comment]
I do not think it is supposed to work this way. I will research what could be done. In the mean time could you please:
* post steps to reproduce your case? 
* How to install eslint and a sample code which you want to format.
* How do you use eslint at the moment?

**Comment by mynkow** [comment]
I am closing this. Let me know if we could revive it at some point
