### ISSUE TITLE
Version 1.19 gets installed instead of 1.21

### ISSUE THREAD

**Issue by Stelzi79** [Elders/VSE-FormatDocumentOnSave#16]
I wanted to update to the latest version 1.21 through the extension manager in VS 2019. It seemed to update fine but I ended up with the old version of 1.19. I made several attempts to force a removal for it (because I thought there was an issue with installing a former manually installed VSIX) but it didn't updated.

Then I downloaded the VSIX manually from https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave and it didn't updated it either. Then I unziped the VSIX and look at which version the VS marketplace gave me and saw this:
![foramt on save](https://user-images.githubusercontent.com/969932/50405973-d462c680-07bc-11e9-8734-8704833dfa23.png)
It seems that the VS marketplace let's you download the version 1.19 and not the version 1.21 as advertised on the vs marketplace.

**Comment by mynkow** [comment]
Ha, this is crazy. Same happened to me. I will bump the version to 1.22 to see if it will fix it. 

I am going to report this to MS.

**Comment by mynkow** [comment]
It worked for me with `1.22`

**Comment by Stelzi79** [comment]
What ever you did it updated to 1.22 this time.
