### ISSUE TITLE
Getting error: "extension/package.json not found inside zip." when trying to install

### ISSUE THREAD

**Issue by BastiPaeltz** [Elders/VSE-FormatDocumentOnSave#17]
Hey,

I would really like to use this extension but when I try to install it via VSIX it just gives me this error message and the extension is not installed.   

I am running VSCode on:
```
Version: 1.30.1
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:07:32.870Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-42-generic
```

**Comment by mynkow** [comment]
Hi @BastiPaeltz 

this extension is for Visual Studio and it is not compatible with VSCode.

You could achieve similar behavior by using the built in support in VSCode. This is the setting=> https://gyazo.com/bfdd0d89132915637aa65bf2cc78e22b
