### ISSUE TITLE
Only allowing specific extensions does not work.

### ISSUE THREAD

**Issue by W4RH4WK** [Elders/VSE-FormatDocumentOnSave#18]
According to the README (Scenario 4) one can specify

    allowed_extensions = .cs
    denied_extensions =

so that only `.cs` files are automatically formatted. This does not work for me.

![image](https://user-images.githubusercontent.com/328798/55471193-80f8e380-5609-11e9-8031-e8161015280a.png)

Even after restarting Visual Studio, `.cpp` files still get auto formatted on save.

Visual Studio version: 15.9.10
Extension version: 1.22

**Comment by mynkow** [comment]
I will check it today

**Comment by mynkow** [comment]
@W4RH4WK indeed there was a bug. I had to do small changes for Scenario4. Please add `.*` to the denied extensions.

The readme is also updated

**Comment by W4RH4WK** [comment]
It seems to work now. Great! Thank you very much.
