### ISSUE TITLE
Supporting multiple commands

### ISSUE THREAD

**Issue by Shereef** [Elders/VSE-FormatDocumentOnSave#19]
The default command is `Edit.FormatDocument` I'd like to be able to add `Edit.RemoveAndSort' after it

**Comment by aroticoz** [comment]
Sounds interesting, we'll look into it as soon as possible.

**Comment by Shereef** [comment]
@aroticoz I hope you don't mind I forked and fixed a build issue in PR #20 and Added this Feature in PR #21 

Please let me know if you have feedback for me! No hurry though I already updated the extension and using it locally

Thanks for an epic extension!

**Comment by Shereef** [comment]
Thanks for merging #21
