### ISSUE TITLE
Cannot install extension on Windows 10, VS 2013 and .NET 4.6.1 (394254) due to .NET Framework version requirements

### ISSUE THREAD

**Issue by ak-hpc** [Elders/VSE-FormatDocumentOnSave#2]
Getting error: The extension requires a version of the .NET Framework that is not installed.

**Comment by sdluxeon** [comment]
Thank, you for your feed back. We will look into this and release a new version for VS 2013

**Comment by mynkow** [comment]
@ak-hpc I uploaded a new version which should not require a specific .net version but .net 4.5 at least. The package is uploaded https://visualstudiogallery.msdn.microsoft.com/3ea1c920-69c4-441f-9979-ccc2752dac56 and it will be great if you can provide a feedback if this worked out.

10x

**Comment by ak-hpc** [comment]
@mynkow, the installation and the extension itself is works now.
Thank you for your quick response.

/solved
