### ISSUE TITLE
Please add new feature.

### ISSUE THREAD

**Issue by debug2030** [Elders/VSE-FormatDocumentOnSave#22]
Hello author:
        Format document as save is great feature! big thanks for dev&&test it.
        I think if you can dev Edit.DeleteBlankLines this feature, it's good for every developmer with visual studio.
        Is there any plan for it? big thanks!

**Comment by mynkow** [comment]
Actually you can use it out of the box. Go to Options inside visual studio and add the command. It is space separated list.

Let me know if this works for you

**Comment by debug2030** [comment]
Hello mynkow:
      Big thanks for reply!
      Following your instruction, it works, but it's not always works.
      Can you check attached picture for double check? big thanks!
![11](https://user-images.githubusercontent.com/50518807/59078303-1158ea80-8911-11e9-9f34-28def5f7e559.JPG)

**Comment by mynkow** [comment]
You need to add the command for the format as well

**Comment by mynkow** [comment]
@debug2030 do you have some feedback on this?
