### ISSUE TITLE
Feature to have key combination save without formatting?

### ISSUE THREAD

**Issue by tendimensions** [Elders/VSE-FormatDocumentOnSave#23]
This is a great extension that I've used for years. Interestingly, I've only recently encountered a scenario where it would be nice if I could do a CTRL-SHIFT-S (or something like it) that would save a file without it re-formatting. Very rarely do I want to save without re-formatting, but when I do it doesn't seem possible without disabling the extension?

Would this be a possible feature to include?

**Comment by mynkow** [comment]
Yes, it is possible. Could you please describe the scenario in details so we could do it the right way?

**Comment by giggio** [comment]
I also need it. For me the problem is that I am maintaining a template file, and I don't want the extension to be remove the `usings` on the top of the file. I am doing not only formatting, but cleanup on save.

**Comment by mynkow** [comment]
@tendimensions @giggio 

How about a key shortcut which Enable/Disable the extension?

**Comment by mynkow** [comment]
Another option which I was considering is to have the plugin disabled when the scroll lock is ON

**Comment by giggio** [comment]
VS Code adds a menu to save without formatting. That would be the most flexible for me.

**Comment by mynkow** [comment]
@giggio what is the shortcut for this operation?

**Comment by giggio** [comment]
<kbd>Ctrl</kbd>+<kbd>k</kbd> <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>s</kbd>

![image](https://user-images.githubusercontent.com/334958/61805228-d3098300-ae0b-11e9-8ed0-f8b69c792e0b.png)

**Comment by mynkow** [comment]
I have a version where the formatting is disabled when the CAPSLOCK is ON. If you think this is a good solution I can release it.

**Comment by giggio** [comment]
I prefer to have a different save option, but this is a good first step. How about releasing it and then evolving it later?

**Comment by mynkow** [comment]
OK, this is now included in v1.25.

Feel free to reopen this issue if you face any problems

**Comment by eduherminio** [comment]
Thanks for this ❤️
