### ISSUE TITLE
Endless loop on File.SaveSelectedItems

### ISSUE THREAD

**Issue by denious** [Elders/VSE-FormatDocumentOnSave#24]
I am trying to auto-format the document with R# and auto-save afterward, which results in a loop.
R# marks a document as edited even if no changes are made, so having ReSharper.ReSharper_ReformatCode as the only command simply makes saving any document impossible! :)

![image](https://user-images.githubusercontent.com/7120854/61982562-25dd6900-afcb-11e9-8110-511e94676408.png)

Two suggestions:

1. Detect _File.SaveSelectedItems_ in the commands.
2. Have an OnBeforeSave and an OnAfterSave command lists, this way I could put ReSharper.ReSharper_ReformatCode in the OnBeforeSave and everything would work out great!

**Comment by mynkow** [comment]
I will try to deliver it this week. Please be patient.

**Comment by mynkow** [comment]
I am looking this right now.

What is the purpose of having `File.SaveSelectedItems` in the commands? Basically the `Commands` are triggered upon save and you are telling the document to be saved again. I think I am missing something here... Please help me understand

**Comment by mynkow** [comment]
@denious ping

**Comment by denious** [comment]
@mynkow My bad, completely missed your first reply!

I don't know how Edit.FormatDocument (A) and ReSharper.ReSharper_ReformatCode (B) are different, but using A the document is saved after formatting, using B leaves the document in an edited state. 

Here's a demo (YT: https://youtu.be/EI6cAfTKDIY), just follow the mouse and I hope it makes sense! I use both Ctrl-S and a manual File > Save to show the differences in behavior.

**Comment by mynkow** [comment]
@denious WAAAAAW, now I see what you mean. I need to think about it.

**Comment by denious** [comment]
@mynkow Let me know what you find or if you need more information!
I am sure many people who use R# would be happy to find out this great extension works for them! 😄

**Comment by mynkow** [comment]
@denious could you please try this version with the `ReSharper.ReSharper_ReformatCode File.SaveSelectedItems` commands

[Elders.VSE_FormatDocumentOnSave.vsix.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/3539891/Elders.VSE_FormatDocumentOnSave.vsix.zip)

**Comment by mynkow** [comment]
Do you end up in a stackoverflow using r# command only in the previous version?

Or plugin crash?

**Comment by mynkow** [comment]
@denious last question. If you execute r# command without format doc on save, is the doc saved afterwards?

**Comment by mynkow** [comment]
I see, do you experience this inconsistent behaviour with the command from the first post?

**Comment by mynkow** [comment]
There is something which R# is doing with the VisualStudio command workflow and I am not able to figure what it is doing. I have tried to find out how their commands operate but did not find anything. Whatever it is it just messes with VisualStudio.

My solution was to track which command was executed per file but I guess it will not help. The other option to execute a PreFormat command or PreSave command will not work at all because we are doing exactly this at the moment.

**Comment by mynkow** [comment]
There is a report that this works OOB without any changes to the code. See the reviews in the extensions store
