### ISSUE TITLE
Partial matches on extensions

### ISSUE THREAD

**Issue by blkbam** [Elders/VSE-FormatDocumentOnSave#25]
allowed_extensions = .cs 
denied_extensions = .*

Having the setup above will match on .css files as well which I'm assuming is because of a partial match. A work around has been to just do:

allowed_extensions = .cs 
denied_extensions = .css .*

**Comment by mynkow** [comment]
Omg, this is bad. I will check. Thanks for reporting this

**Comment by mynkow** [comment]
I just tested this and I am experiencing the following:

With configuration:
allowed_extensions = .cs
denied_extensions = .*

`cs` files are formatted
`css` files are not formatted

Am I missing the point @blkbam ?

**Comment by blkbam** [comment]
hmm. seems that it is working for me now also. sorry about that. i'll play with it a bit more to see if I can reproduce it more but for now let's close this.

**Comment by mynkow** [comment]
Sure, feel free to reopen this issue if you face the problem again. I am also trying something

**Comment by mynkow** [comment]
Actually, I was able to reproduce it

**Comment by blkbam** [comment]
cool! glad to know i wasn't seeing things.

**Comment by mynkow** [comment]
@blkbam I am able to reproduce it only if the `denied_extensions` is left empty and `allowed_extensions = .cs`. This falls into [example 5](https://github.com/Elders/VSE-FormatDocumentOnSave#scenario-5)


However, if I add `.*` to the `denied_extensions` and `allowed_extensions = .cs` it is working properly.

Could you please check the version of the extension

**Comment by blkbam** [comment]
I may have had it set up like that initially. I'm using 1.24.

**Comment by blkbam** [comment]
i did start explicitly listing extensions in the denied list so that we can track which ones will be added to the allow list as we fix it's formatting.

For example:

denied_extensions = .css .html .*

**Comment by mynkow** [comment]
Could you please give it one more try with your initial configuration:
```
allowed_extensions = .cs
denied_extensions = .*
```

**Comment by blkbam** [comment]
that one does work as expected

**Comment by mynkow** [comment]
Perfect. Feel free to reopen this if you face any issues.
