### ISSUE TITLE
[Request] Exclude commands while debugging

### ISSUE THREAD

**Issue by cremor** [Elders/VSE-FormatDocumentOnSave#26]
Could you please add a way to exclude some commands from execution while Visual Studio is in debugging mode?

Use case:
I use the following "commands" setting for your extension: "Edit.FormatDocument Edit.RemoveAndSort".
"Edit.RemoveAndSort" is usually very useful, but actually annoying while debugging because it prevents edit and continue from working. That's why I'd like to not execute it while debugging.

An idea for how this could be done:
Add a new "commands while debugging" setting. Its content will be executed instead of the normal "commands" when Visual Studio is in debugging mode.
To make migration easier the new "commands while debugging" could fall back to the normal "commands" if it is empty.

**Comment by mynkow** [comment]
Do you have an idea how to check if VS is in debug mode?

**Comment by cremor** [comment]
No, sorry. I've never worked with the VS extension SDK.

**Comment by mynkow** [comment]
I found [something ](https://stackoverflow.com/questions/33865333/how-do-i-know-from-my-vsix-that-a-build-will-be-followed-by-a-debug-session)which I need to experiment with.

May be there is better solution. Will keep looking...

**Comment by mynkow** [comment]
Also, I would suggest to have the entire extension disabled while in a debug session and you could enable it manually

**Comment by mynkow** [comment]
![image](https://user-images.githubusercontent.com/183151/69096192-9e75a300-0a5c-11ea-82dd-48d1217da419.png)

**Comment by mynkow** [comment]
@cremor please try the version attached to this comment and let me know if you have any issues


[Elders.VSE_FormatDocumentOnSave.vsix.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/3860852/Elders.VSE_FormatDocumentOnSave.vsix.zip)

**Comment by mynkow** [comment]
This is now available in v2.0

**Comment by cremor** [comment]
The new option works fine, thanks.

But it is not exactly what I had hoped for. As described in my first comment, I'd like to have the "format" command enabled during debugging (because that rarely - if ever - breaks edit and continue). Just the "remove and sort usings" command should be disabled.
