### ISSUE TITLE
Denied Extensions Configuration being ignored

### ISSUE THREAD

**Issue by keeganrowe** [Elders/VSE-FormatDocumentOnSave#27]
When I use a .formatconfig document as per the readme.md or if I set the configuration manually in the options, the Denied Extensions configuration is being ignored.

My .formatconfig:
`root = true

[*.*]
command = Edit.FormatDocument
allowed_extensions = .*
denied_extensions = .json`

My options in Visual Studio: 
![image](https://user-images.githubusercontent.com/5908196/82777905-388e2c00-9e82-11ea-8ee2-cdbfc6c8240d.png)

When I save a JSON file, it is still formatting on save. I have disabled all Visual Extensions except for this one.

I am running version 2.0, installed 6th of May 2020.

**Comment by mynkow** [comment]
@keeganrowe I think you are in [Scenario 1](https://github.com/Elders/VSE-FormatDocumentOnSave#scenario-1)

Also, keep in mind that if you have `.formatconfig` the options in VisualStudio are ignored.

**Comment by keeganrowe** [comment]
> @keeganrowe I think you are in [Scenario 1](https://github.com/Elders/VSE-FormatDocumentOnSave#scenario-1)
> 
> Also, keep in mind that if you have `.formatconfig` the options in VisualStudio are ignored.

Ah, thanks. May I suggest that the full (working) examples at the bottom do not use a set of settings  that are wrong/misleading? ;-)

**Comment by mynkow** [comment]
@keeganrowe 10x for pointing out the issue in readme. Fixed
