### ISSUE TITLE
Using the ReSharper format command doesn't clear the "dirty" flag

### ISSUE THREAD

**Issue by TheFabFab** [Elders/VSE-FormatDocumentOnSave#28]
I changed the command to "ReSharper.ReSharper_ReformatCode".

* The command is triggered as expected - formatting is done
* The file is saved (I am not sure if the first time it is saved before or after formatting)

However, the file will be still marked as changed.

*Software versions used*

Microsoft Visual Studio Professional 2017 
Version 15.9.21
VisualStudio.15.Release/15.9.21+28307.1064

JetBrains ReSharper Ultimate 2020.1.2   Build 201.0.20200506.60635

**Comment by mynkow** [comment]
Do you see the same behavior when executing the resharper command manually?

**Comment by TheFabFab** [comment]
If I first save and then reformat code, I will have the dirty flag, yes.

If I first reformat and then save, I will not have the dirty flag.

**Comment by lilasquared** [comment]
@TheFabFab resharper supports auto format on save natively now, if you still are having trouble with this

**Comment by mynkow** [comment]
Perfect. I am closing this
