### ISSUE TITLE
Allow to disable

### ISSUE THREAD

**Issue by manuc66** [Elders/VSE-FormatDocumentOnSave#32]
Hi,

I think it would be a nice feature to allow disabling formatting from the setting window without needing to disable the extension and restart 

What do you thinks ?

**Comment by mynkow** [comment]
This should be easy to do. Do you have time to submit a PR?

**Comment by manuc66** [comment]
Yes, I'm working on it :)

**Comment by manuc66** [comment]
It's working fine for me, thanks for releasing !
