### ISSUE TITLE
It used to work but now it doesn't

### ISSUE THREAD

**Issue by emmett-b** [Elders/VSE-FormatDocumentOnSave#35]
![image](https://user-images.githubusercontent.com/28929018/109164306-8ec62d80-777a-11eb-9e8d-03dd88a3c3a1.png)

I really like this feature, but it stopped working somehow. I restarted VS. Uninstalled & reinstalled the extension. Didn't fix it.

I changed the VS shortcut for "format document" to alt-shift-f, could it be related?
alt-shift-f works but saving doesn't format :/

**Comment by mynkow** [comment]
@emmett-b which version of VS is installed on your environment?

**Comment by emmett-b** [comment]
Version is VS 2019 16.8.5
![image](https://user-images.githubusercontent.com/28929018/109166157-adc5bf00-777c-11eb-938c-1d5a703089ec.png)

**Comment by mynkow** [comment]
@emmett-b got it. I will update and see what is going on

**Comment by emmett-b** [comment]
The icon I see looks like it's disabled?
![image](https://user-images.githubusercontent.com/28929018/109167384-00ec4180-777e-11eb-8a4e-cda864d49444.png)

Maybe VS complained about synch/asynch load and maybe I clicked on disable?

Let me know if you need more info

**Comment by mynkow** [comment]
I guess something has changed on your end. You could try to investigate by turning on the logs

https://devblogs.microsoft.com/visualstudio/troubleshooting-extensions-with-the-activity-log/

**Comment by emmett-b** [comment]
I just disabled all my other extensions and now it works again, so it suggests some conflict with other extensions?

**Comment by emmett-b** [comment]
Anyway, I'll open a new issue if I can reproduce and pinpoint what's triggering it. Thanks!
