### ISSUE TITLE
Format only modified lines

### ISSUE THREAD

**Issue by seky16** [Elders/VSE-FormatDocumentOnSave#38]
Hello,
please consider adding an option to only format modified text. This can be helpful while working in large codebases where you don't want to cause a conflict or push changes not related to your contribution.

Related: microsoft/vscode#44075

**Comment by mynkow** [comment]
@seky16 I guess you have posted this on the wrong repository. This extension only works with VS. 

VSCode is not supported.

**Comment by seky16** [comment]
No, I'm posting here, because I'm asking for a new feature of this extension in VS. The linked VSCode issue was just adding a context that there's potential interest in such feature and/or adding inspiration.

However if this feature request exceeds scope of this extension then nevermind.
