### ISSUE TITLE
Sort and Removing Usings on Save

### ISSUE THREAD

**Issue by yielder** [Elders/VSE-FormatDocumentOnSave#4]
Hi,

Is that possible to support "Sort and Removing Usings on Save" as well?

That could be quiet useful I guess.

Thanks

**Comment by manuc66** [comment]
I think it could be implemented as an option.

I used this kind of feature long ago and sometime it's too aggressive on code if a conditional DEBUG/RELEASE region needs specific Usings then you may loose those if it's not your active configuration.

Here is an example of : `using System.Diagnostics;` being removed in DEBUG and `using System;` being remove in RELEASE.

```c#
using System.Diagnostics;
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        public void Log(string message)
        {
#if DEBUG
            Console.WriteLine(message);
#else
            EventLog myLog = new EventLog();
            myLog.Source = "MySource";

            // Write an informational entry to the event log.    
            myLog.WriteEntry(message);
#endif
        }
    }
}
```

**Comment by mynkow** [comment]
I personally prefer this to be a separate extension
