### ISSUE TITLE
Problem with .designer.cs

### ISSUE THREAD

**Issue by psikola** [Elders/VSE-FormatDocumentOnSave#41]
I have problem with .designer.cs file (.netstandard20 file).
Formatter always remove usings and i cannot configure it to ignore .designer.cs extension.

example of my designer file:

using System;

namespace EFG.AktionNet.Client.GlobalResources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource
    {
...
	}
}

**Comment by mynkow** [comment]
I guess you have something additional configured because by default this extension does not remove using statements.
