### ISSUE TITLE
Broken on VS 2022 17.3.1

### ISSUE THREAD

**Issue by DomRe** [Elders/VSE-FormatDocumentOnSave#46]
Latest update from VS seems to have broken this extension unfortunately.
No longer formatting document when I edit.

My settings are set at the default.

**Comment by theadin** [comment]
Yup. stopped working for me too :-(

**Comment by mynkow** [comment]
I am updating to VS 2022 17.3.1...

Will get back soon

**Comment by mynkow** [comment]
I have updated the dependencies of the extension and launched a new version 3.3.

Keep in mind that the package has an async loading when launching a new instance of VS. This means that VS could schedule the loading of the extension and it could take up to 30-60 seconds before the extension is initialized.

It is working right now for me. Please check and report any issues...

**Comment by mynkow** [comment]
This breaks the extension for any VS instances which have not been updated. I will rollback the dependencies and will try to check if there are any issues.

**Comment by mynkow** [comment]
Version 3.4 is working with the following VS versions:

17.1.2
17.2.6
17.3.1

**Comment by DomRe** [comment]
Tested with 3.4 on 17.3.1 and its not working for me still unfortunately.

Looks like it's related to #45 though, so ill close this and follow that thread for updates.
