### ISSUE TITLE
Extension doesn't work after upgrade VS to Version 17.3.4

### ISSUE THREAD

**Issue by Alexolut** [Elders/VSE-FormatDocumentOnSave#48]
Formatting not happened on save in VS 2022 Version 17.3.4
In seems that hotkeys are changed recently, since `Ctrl+K, D` make a formatting, but in extension description stated that `Ctrl+E, D` is used for document format. IDK maybe that the root of issue.

**Comment by mynkow** [comment]
Please see this https://github.com/Elders/VSE-FormatDocumentOnSave/issues/47
