### ISSUE TITLE
Visual Studio Crash

### ISSUE THREAD

**Issue by somersby10ml** [Elders/VSE-FormatDocumentOnSave#49]
### Visual Studio
Visual Studio Community 2022(64-bit)
Version: 17.3.5
Microsoft .NET Framework) 4.8.04084
### format document on Save
Version: 3.5

---

The extension is working fine.
I ran into a problem while developing wpf.

try)
1. Top menu -> Project -> Properties (Alt+P+P)
2. After modifying settings in the window, save (Ctrl+S) Visual Studio crashes and restarts.

Message appears after restarting Visual Studio
```
The previous session ended unexpectedly.  
Disabling the format document on Save 3.5 extension may help.  
```

This problem has happened several times.

**Comment by mynkow** [comment]
If possible, could you please try v3.4 if this problem exists there?

**Comment by mynkow** [comment]
Yep, this is because of a hack to workaround a Visual Studio bug. Well, the hack is not working well... sorry

We are tracking the problem here => https://github.com/Elders/VSE-FormatDocumentOnSave/issues/47
