### ISSUE TITLE
Visual Studio 2022 crashing

### ISSUE THREAD

**Issue by Kalabaza** [Elders/VSE-FormatDocumentOnSave#50]
I have Visual Studio Professional 2022 with the Format document on Save extension. It sometimes causes a crash of the complete IDE and this is what I found in the event log:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Elders.VSE_FormatDocumentOnSave.VisualStudioCommandFormatter.OnKeyboardMessage(System.Windows.Forms.Keys, Boolean)
   at Elders.VSE_FormatDocumentOnSave.WindowKeyboardHook.HookProcedure(Int32, IntPtr, IntPtr)
```

All this started to happen more frequently after enabling ccache in the project that I'm working at.

I also have the SonarLint extension installed and trying to analyze a file after it is saved in the IDE.

**Comment by Ivan-Gyoshev** [comment]
yes, the reason for this is that MS have a bug in the Visual Studio and @mynkow has implemented a hack which has this stupid side effect. I told him how to reproduce this.

**Comment by mynkow** [comment]
Yep, this is because of a hack to workaround a Visual Studio bug. Well, the hack is not working well... sorry

We are tracking the problem here => https://github.com/Elders/VSE-FormatDocumentOnSave/issues/47
