### ISSUE TITLE
The extension tries to save the Output Window to a file when starting a build with unsaved files.

### ISSUE THREAD

**Issue by TommyXR** [Elders/VSE-FormatDocumentOnSave#51]
When trying to build a project with some files that are not saved (and thus get saved automatically before the build starts), for each file that is not saved, a pop-up window to specify a path for a file `Output-Build.txt` opens.

This is the same popup as when you press Ctrl+S with focus on the Output Window.

This gets really annoying really fast (for example, if we rename a variable and 30 files get updated, we get this pop-up 30 times!!!).

This only started happening after updating from VS 17.3.3 to 17.3.6. It does not happen when the extension is disabled (by uninstalling it or having Caps Lock on).

A workaround is to change the tab to not have the Output Window visible.

**Comment by Krusty93** [comment]
Same here

**Comment by mynkow** [comment]
Yep, this is because of a hack to workaround a Visual Studio bug. Well, the hack is not working well... sorry

We are tracking the problem here => https://github.com/Elders/VSE-FormatDocumentOnSave/issues/47
