### ISSUE TITLE
Asking to save output-build.txt after building the project with this extension

### ISSUE THREAD

**Issue by sunnamed434** [Elders/VSE-FormatDocumentOnSave#53]
Steps to reproduce:
1. Build project/run
2. Dialog that asking me to save `Output-Build.txt`, sometimes I can`t close it and getting tons of errors
3. Visual studio become laggy/freezing
4. Crash
5. Launch visual studio again
6. Visual studio says to disable FormatDocumentOnSave extension to fix this problem, after disabling it everything works fine

**Comment by mynkow** [comment]
What is the VS version and the extension version?

**Comment by dmitryvhf** [comment]
VS2022(Preview5),VSE 3.6

I have 2 and 3. But i dont know - this problem Preview5 or VSE. This problem not existed on VS2022(Preview4).
I dont stop VSE for finding source of problem.

**Comment by devbotas** [comment]
I have the exact same problem with 17.3.6 and 3.6.

**Comment by sunnamed434** [comment]
When I was on project with multiple frameworks .NET Core, .NET Framework, Maui Blazor (I can`t even normally work there with this extension, don`t think that I`m trying to say this is bad extension, no) - I used to be have crashes and freezing + lags, but when I moved to working with another project an .NET Framework Im having only dialog with asking me about save smth to somewhere `Output-Build.txt` no crashes there, sometimes this is not asking me to save and sometimes asking, idk this is working so-so-so weird

**Comment by mynkow** [comment]
ok, could you please watch for the following:
- do you get this behavior if you are working with only *.cs files
- do you get this behavior when you are working with any XML like files (*.cshtml, *.razor, *.xml etc.)

**Comment by sunnamed434** [comment]
> ok, could you please watch for the following:
> 
>     * do you get this behavior if you are working with only *.cs files
> 
>     * do you get this behavior when you are working with any XML like files (*.cshtml, *.razor, *.xml etc.)

Ok, np I will do it

**Comment by mynkow** [comment]
ok, I am disabling the XML support. My internal feeling is that it causes the problems. Will do this in v3.8. Should be there in few minutes.

**Comment by sunnamed434** [comment]
And also Im using config in project with .NET Framework .NET Core and Maui Blazor

File: `.formatconfig`

Content inside of config:
root = true

[*.*]
enable = true
command = Edit.FormatDocument
allowed_extensions = 
denied_extensions = .js .html .razor .razor.css .css



And seems no problems when Im trying to build/run project when my main window is *.razor

**Comment by devbotas** [comment]
I can trigger the same popup if I manually click Ctrl+S on a focudes "Output" window. I guess the plugin somehow decides that Output window has changed and needs saving?..

**Comment by devbotas** [comment]
> ok, I am disabling the XML support. My internal feeling is that it causes the problems. Will do this in v3.8. Should be there in few minutes.

I have tried on a project which is a pure dll library without any XML files. Still the same problem...

**Comment by devbotas** [comment]
Apparently, with the fresh 3.8 plugin version popups are gone for me.

**Comment by mynkow** [comment]
closing this. In future I might play again with the XML files to make them work without getting this behavior.
