### ISSUE TITLE
Command for Fix All Auto-Fixable Problems 

### ISSUE THREAD

**Issue by NoelAbrahams** [Elders/VSE-FormatDocumentOnSave#54]
Hi

In TypeScript files I have the following option available on a context menu:

![image](https://github.com/Elders/VSE-FormatDocumentOnSave/assets/1106823/86ddf68a-2914-4d46-8480-b9ad3b982b7e)

Is there a way to configure VSE-FormatDocumentOnSave to run this command on save?

Something like
```
command = Edit.FormatDocument Edit.autofix???
```

**Comment by NoelAbrahams** [comment]
Yes, but I'm actually after an auto-fix command. Not sure if there is one.

**Comment by mynkow** [comment]
I am not aware how this actually works.  If you can execute it from the command line then we can make it work somehow.

**Comment by mynkow** [comment]
Feel free to reopen if you need help
