### ISSUE TITLE
Doesn't format on VS 2022 17.7.0

### ISSUE THREAD

**Issue by Alexolut** [Elders/VSE-FormatDocumentOnSave#56]
Seems that VS broke something again, saving doesn't perform formatting on recently released VS [17.7.0](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.7.0)

**Comment by mynkow** [comment]
Wow, that will be a pain... Checking...

**Comment by mynkow** [comment]
Quick update:
1. I have updated VS to v 17.7.0. When starting the extension there were hundreds of error about the kernel. I guess OS stuff. But the extension is working on my machine.
2. I have 2 team mates with version 17.7.0 where the extension stopped working:
2.1. Team member A said that after couple of days the extension started working.
2.2 I have compiled a new version and passed it to team member B but it is still not working there.

I guess we are lucky that we have a non working version locally so we will debug it to check what is going on. Till then here is a version compiled with the latest VS (I am 99% sure that it will not work where it is broken but we have to try)

[Elders.VSE_FormatDocumentOnSave.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/12343282/Elders.VSE_FormatDocumentOnSave.zip)

**Comment by toughengineer** [comment]
The other extension stopped working as well. 😩

When I open a single file (or a _small_ solution it seems) both extensions work.
But when I open a large solution (150 projects in my case) both extensions stop working.
**Edit→Advanced→Format Document** (Ctrl+K,Ctrl+D) works always.
I would bet it's VS's fault.

**Comment by mynkow** [comment]
Bad news people.

![image](https://github.com/Elders/VSE-FormatDocumentOnSave/assets/183151/450fe111-d422-4fcd-899c-fd569e2ac99c)

**Comment by mynkow** [comment]
I totally regret updating my VS to v17.7.0.

Now I am not able to open the UI and manage nuget packages.
ctrl+f for search throws an exception

Trying to rollback. I will wait for the next version and hopefully most of the issue will be gone.

Regarding the extension, when the error from the above screenshot (which kills the entire VS process for me) does NOT occur I get windows errors in the extension about windows updates and EngineStorage error.

**Comment by mynkow** [comment]
More updates. There are several packages which might fix the extension issues when I am able to update them. Right now they depend on a package which is not yet published in nuget:

NU1102: Unable to find package Microsoft.Build.Framework with version (>= 17.7.2)
  - Found 46 version(s) in nuget.org [ Nearest version: 17.7.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1102: Unable to find package Microsoft.NET.StringTools with version (>= 17.7.2)
  - Found 8 version(s) in nuget.org [ Nearest version: 17.7.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
Package restore failed. Rolling back package changes for 'Elders.VSE-FormatDocumentOnSave'.

![image](https://github.com/Elders/VSE-FormatDocumentOnSave/assets/183151/c2589441-3dca-453f-9e41-ddffe4416262)

**Comment by mynkow** [comment]
And... here is a version where the extension is working for the current file. It will not work for SaveAll functionality,

[Elders.VSE_FormatDocumentOnSave.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/12345751/Elders.VSE_FormatDocumentOnSave.zip)

**Comment by Justin-Randall** [comment]
I have verified that this zip works in my own case. Thanks for the workaround!

**Comment by mynkow** [comment]
@Alexolut yeah, it depends if you hit the exception [here](https://github.com/Elders/VSE-FormatDocumentOnSave/issues/56#issuecomment-1678842833) which is a random behavior.

**Comment by mynkow** [comment]
I have started a conversation here:
https://developercommunity.visualstudio.com/t/Random-exceptions-after-upgrading-to-vs1/10448113

**Comment by mynkow** [comment]
# v3.10
* Disables all additional features for Visual Studio versions with broken SDK
* The features will be automatically enabled when Visual Studio SDK has the proper version


https://developercommunity.visualstudio.com/t/Format-on-Save-extension-no-longer-wor/10448305#T-ND10467142
