### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by gorkemhacioglu** [Elders/VSE-FormatDocumentOnSave#57]
Hello,

I have this error.
![image](https://github.com/Elders/VSE-FormatDocumentOnSave/assets/32572262/da6061c9-11e1-46f7-bd6d-44fc6d5c274d)

`SetSite failed for package [FormatDocumentOnSavePackage]Source: 'Elders.VSE_FormatDocumentOnSave' Description: Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.AsyncPackage.get_JoinableTaskFactory()'.
System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.AsyncPackage.get_JoinableTaskFactory()'.
   at Elders.VSE_FormatDocumentOnSave.FormatDocumentOnSavePackage.<InitializeAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Elders.VSE_FormatDocumentOnSave.FormatDocumentOnSavePackage.InitializeAsync(CancellationToken cancellationToken, IProgress```1 progress)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)`
   
Windows 11
VS 2022 17.6.4
Extension version 3.10

**Comment by gorkemhacioglu** [comment]
This build solved my problem
https://github.com/Elders/VSE-FormatDocumentOnSave/issues/56#issuecomment-1679126763

**Comment by qbolec** [comment]
I see the issue is Closed since last year, yet I've installed the extension this year.
AFAICT I am on Extension version 3.11 and VS 17.8.6 and face a very similar problem:
```
SetSite failed for package [FormatDocumentOnSavePackage]Source: 'Elders.VSE_FormatDocumentOnSave' Description: Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.AsyncPackage.get_JoinableTaskFactory()'. System.MissingMethodException: Method not found: 'Microsoft.VisualStudio.Threading.JoinableTaskFactory Microsoft.VisualStudio.Shell.AsyncPackage.get_JoinableTaskFactory()'. at Elders.VSE_FormatDocumentOnSave.FormatDocumentOnSavePackage.<InitializeAsync>d__2.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at Elders.VSE_FormatDocumentOnSave.FormatDocumentOnSavePackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```
Could you please share how to resolve it?

**Comment by mynkow** [comment]
@gorkemhacioglu @qbolec 
For last 12-18 months microsoft did a number of breaking changes in visual studio. I do not think their semantic versioning is working properly so every time I see a minor bump I expect breaking changes. I have tested the latest version of the extension with previous version of VS and it is just not loading. There are assembly changes in VS code base where they have changed the signature of some methods. Long story short, from now on I will be posting the version of VS which I have the extension tested with. Like this:
https://github.com/Elders/VSE-FormatDocumentOnSave/releases/tag/v3.11
