### ISSUE TITLE
Is extension working?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [Elders/VSE-FormatDocumentOnSave#58]
In the marketplace https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave
The top line is 
IMPORTANT - Extension is not working !!!

Is it correct or should be removed?

**Comment by mynkow** [comment]
oh, it is working!

**Comment by mynkow** [comment]
just test v3.11 with Microsoft Visual Studio Community 2022 (64-bit) - Version 17.9.4 and everything is working like 6 months ago.
