### ISSUE TITLE
Extension does not respect insert_final_newline = false setting

### ISSUE THREAD

**Issue by alexsorokoletov** [Elders/VSE-FormatDocumentOnSave#6]
Hi!
I've installed the extension and added an .editorconfig to the root folder (same level, as .sln file).

```
; Check http://editorconfig.org/ for more informations
; Top-most EditorConfig file
; Use with VisualStudio https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328
root = true

; 2-column space indentation
[*]
indent_style = space
indent_size = 3
trim_trailing_whitespace = true
insert_final_newline = false
```

Still, after saving file, I get newline in the last line of the file.
All other settings seem to work

Please advise

**Comment by mynkow** [comment]
The extension actually does not touch the source code. It just invokes the visual studio command to format the current file. Could you please try to format the document from the `Edit` menu and see if the line is added?

**Comment by alexsorokoletov** [comment]
@mynkow thanks for quick reply.
Turned out, that was indeed VS 2017 playing tricks with me and `.editorconfig`

Thank you for the extension, really helpful. In fact, I've written similar for Xamarin Studio - as I miss this functionality in any IDE.

Let's close the issue
