### ISSUE TITLE
ARM64 Support?

### ISSUE THREAD

**Issue by christophwille** [Elders/VSE-FormatDocumentOnSave#60]
Would that be possible - like https://marketplace.visualstudio.com/items?itemName=neuecc.OpenonGitHub

**Comment by mynkow** [comment]
Sure, try this version and let me know if it is working as expected and I will push it officially

[Elders.VSE_FormatDocumentOnSave.vsix.zip](https://github.com/user-attachments/files/16192700/Elders.VSE_FormatDocumentOnSave.vsix.zip)

**Comment by christophwille** [comment]
Will give it a shot (sorry, not possible before Sunday, I only took my x64 machine with me for the weekend).

**Comment by christophwille** [comment]
Detects and installs properly:

![image](https://github.com/user-attachments/assets/b5e6c4d1-2d05-4e8d-a5cc-01f8c070fd87)

and also kicks in appropriately. Thanks!

**Comment by mynkow** [comment]
Nice, I will update the marketplace
